### ISSUE TITLE
Firewall (OVA/AMI with packer)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-Releases#16]

**Comment by Helmy1998** [comment]
https://github.com/k8-proxy/k8-vmware-firewall/pull/7

**Comment by Helmy1998** [comment]
https://github.com/k8-proxy/k8-vmware-firewall/pull/7

**Comment by Helmy1998** [comment]
https://github.com/k8-proxy/k8-vmware-firewall/pull/7
