### ISSUE TITLE
Test the customer provided certificate route

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-Releases#235]

**Comment by hongson1981** [comment]
Update the progress :
- Finish round one for customer provided certificate route : Installation with customize cert + uninstallation : success
- Next step : Round 2 with customize cert  is disable, but customer provided certificate still exists in folder certs , script will auto generate new certificates and overwrite old certificates : will do it tomorrow

**Comment by hongson1981** [comment]
Hi @GINAGC 
Testing done. Summary scenarios below :
1. enable_customer_cert=false : Script  auto generate certificates and apply to pointing domain
2. enable_customer_cert=true : Script get certificates from certs folder and apply to pointing domain
3. enable_customer_cert=true and there are not certificates in certs folder : Error show during deploy  ```
Error: Error running command '/bin/bash ./scripts/k8s_scripts/file-drop-secrets.sh fd-clu-sha3': exit status 1. Output: namespace/icap-filedrop created
namespace/ingress-nginx created
Switched to context "fd-clu-sha3".
error: Cannot read file certificate.crt, open certificate.crt: no such file or directory
```

**Comment by GINAGC** [comment]
@samarthdd to review the information shared by Son Ha.
