### ISSUE TITLE
File drop and ICAP server OVAs with CentOS 7 (latest version) 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-Releases#78]
- this is needed for ICAP server and File drop, but ICAP server has higher priority.
- please create a new branch for this, we still need the other versions.
- We will test if these OVAs can be imported in AWS and ESXi and if not, will have to downgrade versions.

**Comment by MariuszFerdyn** [comment]
Be sure that always `HWADDR` is removed from ` /etc/sysconfig/network-scripts/ifcfg-eth0`.

**Comment by GINAGC** [comment]
@pranaysahith can you confirm the above?

**Comment by pranaysahith** [comment]
yes, the scripts are already updated.

**Comment by GINAGC** [comment]
OK, I am closing this one. Thank you
